version: '3.7'
services:
  db:   #Сервис базы
    image: mysql:8.0    #Выбираем готовый образ mysql
    command: --default-authentication-plugin=mysql_native_password      #Переопределяем старндартное значение
    container_name: db  #Имя контейнера
    #restart: unless-stopped    #Политика перезапуска - пока не остановлен
    environment:        #Дополнительные переменные, не чувствительные
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wp_password
    volumes:
      - db_data:/var/lib/mysql

  wordpress: #Сервис приложения
    depends_on:
      - db
    container_name: wordpress-production
    image: dmitronik/wordpress:latest
    #restart: unless-stopped    #Политика перезапуска - пока не остановлен
    ports:      #Переадресация портов с хоста в контейнер
      - "80:80"
    environment: #Переменные передающиеся на вход контейнера
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wp_password
      - WORDPRESS_DB_NAME=wordpress
    volumes: #Общий том между контейнером и хостом
      - wordpress:/var/www/html

volumes:
  db_data:
  wordpress:

