name: Docker Image CI

on:
  push:
    branches-ignore: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy in EC2
        env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
          HOSTNAME : ${{ secrets.EC2_PROD_HOSTNAME  }}
          USER_NAME : ${{ secrets.EC2_PROD_USER_NAME  }}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
          
            #Now we have got the access of EC2 and we will start the deploy .
            cd /home/ubuntu/App &&
            docker compose down &&
            curl -o compose-production.yml -fL https://raw.githubusercontent.com/DMiTRONiK/DevOps-experience/main/wordpress/compose-production.yml &&
            docker compose -f compose-production.yml up -d --build 
          '



