name: Docker Image CI

on:
  push:
    branches: 
      - main

jobs:

  deploy_to_prod:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Deploy in EC2
        env:
          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
          HOSTNAME : ${{ secrets.EC2_PROD_HOSTNAME  }}
          USER_NAME : ${{ secrets.EC2_PROD_USER_NAME  }}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
          
            #Now we have got the access of EC2 and we will start the deploy .
            cd /home/ubuntu/App/DevOps-experience/wordpress &&
            sh -c "
              if [ -s compose-production.yml ]; then
                docker compose -f compose-production.yml down
              fi
            "
            git fetch origin &&
            git reset --hard origin/main
            docker compose -f compose-production.yml up -d --build
          '



